language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6.2

install:
  - pip install psycopg2
  - pip install django==$DJANGO_VERSION
  - pip install coverage coveralls
  - pip install django-safedelete==0.1.2

script:
script:
  - coverage run --source=django_nopassword setup.py test
  - coverage report


before_script:
  - psql -c 'create database django_nopassword;' -U postgres

after_success: coveralls
